AWSTemplateFormatVersion: '2010-09-09'
Description: 'Stack básica para o desafio DIO - Criação de uma instância EC2'

Resources:
  MinhaInstanciaServidor:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c55b159cbfafe1f0 # Exemplo de ID de AMI Linux (pode variar por região)
      Tags:
        - Key: Name
          Value: DesafioDIO-CloudFormation
